version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: weather_json
        external:
            location: "D:/MyData/Ahmads/Projects/DBT/Weather/ingestion/data/raw/weather/*.json"
            format: json
      - name: air_quality_json
        external:
            location: "D:/MyData/Ahmads/Projects/DBT/Weather/ingestion/data/raw/air_quality/*.json"
            format: json
